#!/usr/bin/env python3
"""
For each area_changes page:
1. Remove any ### Trainer sections with a "Pokémon | Item | Moves" header
   (generated by a previous version of this script).
2. For trainer rows without an existing detailed section, append the last 4
   level-up moves directly into each Pokémon's table cell in the summary table.

Trainers with existing detailed sections (those that have Nature/Ability
columns) are left untouched.
"""

import re
import sys
from pathlib import Path

AREA_DIR = Path("docs/area_changes")
POKEMON_DIR = Path("docs/pokemons")


def get_levelup_moves(pokemon_num: int, level: int) -> list:
    """Return the last ≤4 level-up moves learned at or below `level`."""
    path = POKEMON_DIR / f"{pokemon_num:03d}.md"
    if not path.exists():
        return []
    text = path.read_text()
    m = re.search(
        r'## Level Up Moves\n\nLevel.*?\n---.*?\n(.*?)(?=\n## )',
        text, re.DOTALL
    )
    if not m:
        return []
    moves = []
    for line in m.group(1).split('\n'):
        parts = [p.strip() for p in line.split('|')]
        if len(parts) < 2:
            continue
        try:
            move_level = int(parts[0])
        except ValueError:
            continue
        if move_level > level:
            continue
        name = re.sub(r'\[([^\]]+)\]', r'\1', parts[1].strip())
        if name:
            moves.append(name)
    return moves[-4:]


def extract_plain_name(cell: str) -> str:
    """Strip images/links from a trainer name cell to get a plain name."""
    cell = re.sub(r'!\[\]\[[^\]]*\]', '', cell)
    cell = re.sub(r'<br\s*/?>', ' ', cell, flags=re.IGNORECASE)
    m = re.search(r'\[([^\]]+)\]', cell)
    if m:
        return m.group(1).strip()
    return cell.strip()


def parse_pokemon_cell(cell: str):
    """Return (cell_text, pokemon_num, level) or None for non-Pokémon cells."""
    cell = cell.strip()
    if not cell or cell == '&nbsp;':
        return None
    num_m = re.search(r'!\[\]\[(\d{3})\]', cell)
    lv_m = re.search(r'Lv\.\s*(\d+)', cell)
    if num_m and lv_m:
        return (cell, int(num_m.group(1)), int(lv_m.group(1)))
    return None


def remove_generated_sections(lines: list) -> list:
    """Remove ### Name sections whose first table row is 'Pokémon | Item | Moves'."""
    result = []
    i = 0
    while i < len(lines):
        m = re.match(r'^### (.+)$', lines[i])
        if m:
            # Peek at the next non-blank line
            j = i + 1
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j < len(lines) and lines[j].strip() == 'Pokémon | Item | Moves':
                # Generated section — drop it, skip until next heading
                while result and not result[-1].strip():
                    result.pop()
                i += 1
                while i < len(lines):
                    if re.match(r'^#{1,3}\s', lines[i]):  # next heading
                        break
                    if lines[i].strip() and '|' not in lines[i]:  # non-table content
                        break
                    i += 1
                continue
        result.append(lines[i])
        i += 1
    return result


def find_detailed_trainers(lines: list) -> set:
    """
    Return plain names of trainers with existing detailed sections
    (identified by a header row containing 'Nature' or 'Ability').
    """
    detailed = set()
    for i, line in enumerate(lines):
        m = re.match(r'^#{1,4}\s+(.+)$', line)
        if m:
            name = m.group(1).strip()
            j = i + 1
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j < len(lines) and ('| Nature' in lines[j] or '| Ability' in lines[j]):
                detailed.add(name)
    return detailed


def strip_table_moves(lines: list) -> list:
    """Remove any <ul>...</ul> blocks that were previously added to summary table cells."""
    result = []
    in_table = False
    for line in lines:
        stripped = line.lstrip()
        leading = len(line) - len(stripped)
        if leading >= 4:
            in_table = False
        elif re.match(r'Trainer\s*\|', stripped):
            in_table = True
        elif in_table and '|' not in stripped:
            in_table = False
        if in_table and '|' in stripped and not re.match(r'[-:]+\s*\|', stripped):
            line = re.sub(r'<ul>(?:<li>[^<]*</li>)*</ul>', '', line)
        result.append(line)
    return result


def process_file(filepath: Path, dry_run: bool = False) -> bool:
    original = filepath.read_text()
    lines = original.splitlines()

    # Step 1: Remove previously generated simple sections
    lines = remove_generated_sections(lines)
    text = re.sub(r'\n{3,}', '\n\n', '\n'.join(lines))
    lines = text.splitlines()

    # Step 2: Strip any moves previously injected into summary table cells
    lines = strip_table_moves(lines)

    # Step 3: Find trainers that already have detailed sections
    detailed_trainers = find_detailed_trainers(lines)

    # Step 4: Add moves inline to Pokémon cells for simple trainers
    in_table = False
    new_lines = []

    for line in lines:
        stripped = line.lstrip()
        leading = len(line) - len(stripped)

        if leading >= 4:
            in_table = False
            new_lines.append(line)
            continue

        if re.match(r'Trainer\s*\|', stripped):
            in_table = True
            new_lines.append(line)
            continue

        if not in_table:
            new_lines.append(line)
            continue

        if re.match(r'[-:]+\s*\|', stripped):
            new_lines.append(line)
            continue

        if '|' not in stripped:
            in_table = False
            new_lines.append(line)
            continue

        cells = stripped.split('|')
        if len(cells) < 2:
            in_table = False
            new_lines.append(line)
            continue

        plain = extract_plain_name(cells[0])
        if not plain or plain in detailed_trainers:
            new_lines.append(line)
            continue

        # Add moves to each Pokémon cell
        new_cells = [cells[0]]
        for c in cells[1:]:
            parsed = parse_pokemon_cell(c)
            if parsed:
                cell_text, num, level = parsed
                moves = get_levelup_moves(num, level)
                if moves:
                    moves_html = '<ul>' + ''.join(f'<li>{mv}</li>' for mv in moves) + '</ul>'
                    cell_text = cell_text.rstrip() + moves_html
                new_cells.append(' ' + cell_text + ' ')
            else:
                new_cells.append(c)

        new_lines.append('|'.join(new_cells))

    result = '\n'.join(new_lines) + '\n'
    if result == original:
        return False

    if not dry_run:
        filepath.write_text(result)
    return True


if __name__ == '__main__':
    dry_run = '--dry-run' in sys.argv
    targets = [Path(p) for p in sys.argv[1:] if not p.startswith('--')]
    if not targets:
        targets = sorted(AREA_DIR.glob('*.md'))

    modified = 0
    for f in targets:
        if process_file(f, dry_run=dry_run):
            modified += 1
            print(f"  {'(dry) ' if dry_run else ''}{f.name}")

    print(f"\n{'Would modify' if dry_run else 'Modified'} {modified} files")
